CREATE TABLE service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK (length(btrim(name)) > 0),
    description VARCHAR(500) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX uq_service_categories_name ON service_categories (lower(name));

CREATE TABLE workshop_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES service_categories(id) ON DELETE RESTRICT,
    name VARCHAR(120) NOT NULL CHECK (length(btrim(name)) > 0),
    description VARCHAR(1000) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX uq_workshop_services_category_name
    ON workshop_services (category_id, lower(name));
