CREATE TABLE client_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,
    contact_email VARCHAR(254) NOT NULL,
    address_line VARCHAR(150) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    city VARCHAR(80) NOT NULL,
    has_company_data BOOLEAN NOT NULL,
    company_name VARCHAR(150),
    tax_id VARCHAR(32),
    billing_address_line VARCHAR(150),
    billing_postal_code VARCHAR(20),
    billing_city VARCHAR(80)
);
