CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    make VARCHAR(80) NOT NULL,
    model VARCHAR(80) NOT NULL,
    production_year INTEGER NOT NULL CHECK (production_year >= 1886),
    registration_number VARCHAR(20) NOT NULL,
    vin VARCHAR(17)
);

CREATE UNIQUE INDEX uq_vehicles_owner_registration
    ON vehicles (owner_id, upper(registration_number));
CREATE UNIQUE INDEX uq_vehicles_owner_vin
    ON vehicles (owner_id, upper(vin))
    WHERE vin IS NOT NULL;
