ALTER TABLE vehicles
    ADD CONSTRAINT uq_vehicles_id_owner UNIQUE (id, owner_id);

CREATE TABLE appointment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference UUID NOT NULL UNIQUE,
    requester_type VARCHAR(20) NOT NULL
        CHECK (requester_type IN ('CLIENT', 'GUEST')),
    client_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
    vehicle_id BIGINT,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    phone_number VARCHAR(30),
    contact_email VARCHAR(254),
    vehicle_make VARCHAR(80) NOT NULL,
    vehicle_model VARCHAR(80) NOT NULL,
    vehicle_production_year INTEGER NOT NULL
        CHECK (vehicle_production_year >= 1886),
    vehicle_registration_number VARCHAR(20) NOT NULL,
    vehicle_vin VARCHAR(17),
    requested_start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    current_start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    problem_description VARCHAR(2000) NOT NULL,
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('PENDING', 'TIME_PROPOSED', 'CONFIRMED', 'REJECTED')),
    staff_message VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    staff_action_at TIMESTAMP WITH TIME ZONE,
    staff_action_by_id BIGINT REFERENCES app_users(id),
    client_confirmed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_appointment_vehicle_owner
        FOREIGN KEY (vehicle_id, client_id) REFERENCES vehicles(id, owner_id),
    CONSTRAINT ck_appointment_requester_data CHECK (
        (requester_type = 'CLIENT' AND client_id IS NOT NULL AND vehicle_id IS NOT NULL)
        OR
        (requester_type = 'GUEST' AND client_id IS NULL AND vehicle_id IS NULL)
    ),
    CONSTRAINT ck_appointment_contact CHECK (
        phone_number IS NOT NULL OR contact_email IS NOT NULL
    )
);

CREATE UNIQUE INDEX uq_appointment_requests_active_slot
    ON appointment_requests (current_start_at)
    WHERE status IN ('PENDING', 'TIME_PROPOSED', 'CONFIRMED');

CREATE INDEX ix_appointment_requests_client_created
    ON appointment_requests (client_id, created_at DESC);

CREATE INDEX ix_appointment_requests_status_created
    ON appointment_requests (status, created_at);
